import './bootstrap';
import './edit-day';
import './destroy-day';
import './logout';
import './attendance';
import './attendance-camera';
import './attendance-photo';
import './attendance-minutes';
import './accountPage';
import './cabang.index';
import './pasangan.index';
import './timeLedger'
import './ledger-modal'